using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IdealSysApp.Models.Entities
{
  public class ProductImage : BaseEntity
  {
    /// <summary>
    /// AutoGenerated Name By Guid or Folder extension
    /// </summary>
    [MaxLength(100)]
    public string Name { get; set; }
    /// <summary>
    /// File Original Name Default
    /// </summary>
    public string DisplayName { get; set; }
    /// <summary>
    /// Full path for Image
    /// </summary>
    public string Url { get; set; }

    /// <summary>
    /// Extension Image (bmp,jpg,png)
    /// </summary>
    [MaxLength(10)]
    public string Extensions { get; set; }
    /// <summary>
    /// Size in KB
    /// </summary>
    public decimal Size { get; set; }
    public long ProductId { get; set; }
    public virtual Product Product { get; set; }
  }
}
